### ISSUE TITLE
[QUESTION] Fetch email but don't mark it as read

### ISSUE THREAD

**Issue by x44x45x41x4E** [mailman/mailman#114]
As I've seen in the documentation of Mail gem which is one of the dependency of Mailman, I can set in my imap config to fetch all the emails in my inbox and enable the `:read_only` option to true. What are the flags the I could use in IMAP for Mailman to fetch emails but don't mark them as read? Sorry if this is not an issue at all but I can't seem to find a relevant answer that uses this Gem. Thanks.

**Comment by nonnenmacher** [comment]
I had a similar problem, for having imap messages processed, not been seen again if there was an exception during processing.

I used the FLAGGED marker, for imap messages, and filtered on both 'unseen' and 'not flagged', and mark messages that do not raise an exception as 'flagged'
as Mainman, will mark them by default 'seen', the double condition, make easy
to determine if a mail was handled with 'problems' or was handled properly.

i.e  messages that are marked 'read' but not 'flagged' are problematic messages.

The trick is around method `Mailman:Receiver:IMAP#get_messages`

The code read as : 

     ```
     @connection.search(@filter).each do |message|
          body = @connection.fetch(message, "RFC822")[0].attr["RFC822"]
          @processor.process(body)
          @connection.store(message, "+FLAGS", @done_flags)
        end
    ```

if you set `@filter` to search for UNSEEN and UNFLAGGED and `@done_flags` to set both flags, you meet your conditions on the next pass, only if `@processor.process` succeeded.

So the answer for this one, is to add : 
   
    ```
         done_flags: ['SEEN','FLAGGED']
         filter: ['UNSEEN','UNFLAGGED']
    ````

 into your `Mailman.config.imap` options Hash.

**Comment by nonnenmacher** [comment]
NOTE : it could be handy to have an handle to the current `@connection` of the message handler, from inside Mailman.middleware.

It could be like a Rack middleware, where an ENV like parameters could catch current message handling environment and so have access to such member.

or having the `call` method be defined as 

   ``` def call(mail, handler accessor)```

Given that, it could be much easier, to use the underlying Net/IMAP class, to move handled messages in some folders (e.g 'done'/'errors') and be fine with default 'seen/unseen' processing.

I guess POP3 and MailDir handler could use 'delete/forward' operation to handle the same kind of logic.

**Comment by x44x45x41x4E** [comment]
Hi nonnenmacher! Thanks! I actually saw that option in the code but I wasn't sure how to add it in my config hash. Thanks again!
