### ISSUE TITLE
Move to mailman organization

### ISSUE THREAD

**Issue by titanous** [mailman/mailman#120]
I managed to get https://github.com/mailman and I'm planning to move the repo there today. There will probably be some minor changes required in the repo after the move.

**Comment by jphastings** [comment]
Ahh, thanks for the heads up.

**Comment by titanous** [comment]
Transferred. Sorting out the rename in Travis now.

**Comment by titanous** [comment]
Travis rename complete, I've subbed out all links I found in the repo.
