### ISSUE TITLE
Is that possible to receive emails from different email addresses?

### ISSUE THREAD

**Issue by KranthiKishore** [mailman/mailman#133]
Hi, I'm creating unique email address to each registered user. If users sends an email to the unique email address is that possible to receive in rails with this gem?

**Comment by serg2801** [comment]
@KranthiKishore same trouble... Have you fond the answer?

**Comment by KranthiKishore** [comment]
@serg2801 I solved it using `griddler` and godaddy.

**Comment by Mic92** [comment]
You can configure your mail server to send emails to the same internal user.
I did this once using virtual-regex in postfix:
http://serverfault.com/questions/144325/how-to-redirect-all-postfix-emails-to-one-external-email-address

Apart from that catch-all addresses might help too.
