### ISSUE TITLE
[Question] Mailman with Mailbox

### ISSUE THREAD

**Issue by kirantpatil** [mailman/mailman#145]
Hi,

Has anybody integrated Mailman with Mailbox (https://github.com/mailboxer/mailboxer)?

Thanks.

**Comment by Mic92** [comment]
What kind of integration is needed?

**Comment by ajazshaik** [comment]
Has anybody integrated Mailman with Mailbox to receive email from pop3?

**Comment by Mic92** [comment]
But this mailbox gem sends stuff and mailman process incoming emails. So the gems set looks orthogonal to me and can work independent.
