### ISSUE TITLE
Pass options to underlying implementation (e.g. to skip ssl verification)

### ISSUE THREAD

**Issue by wvengen** [mailman/mailman#93]
I'm connecting to an ssl server with a self-signed certificate, which currently fails on checking certificate validity. When options like `verify_mode` can be passed to [`Net::IMAP`](http://ruby-doc.org/stdlib-2.1.0/libdoc/net/imap/rdoc/Net/IMAP.html#new-method) (which passes it in turn to [`SSLContext`](http://www.ruby-doc.org/stdlib-2.0/libdoc/openssl/rdoc/OpenSSL/SSL/SSLContext.html#method-i-set_params)), this should be able to work. Haven't tested this though.

**Comment by jphastings** [comment]
Looks like this has been closed with #111 so I'll close this issue.
